// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package parser

import "encoding/json"
import "fmt"

// Configuration of an Atomic Red Team test case
type AtomicRedTeamSchemaJson struct {
	// Atomic Red Team test case GUID (auto_generated_guid from the test definition)
	Guid string `json:"guid" yaml:"guid" mapstructure:"guid"`

	// Inputs for the Atomic Red Team test case
	Inputs map[string]string `json:"inputs,omitempty" yaml:"inputs,omitempty" mapstructure:"inputs,omitempty"`

	// MITRE ATT&CK technique ID (e.g., T1059.004)
	Technique string `json:"technique" yaml:"technique" mapstructure:"technique"`

	// An optional commit hash pointing to the Atomic Red Team version to use. Will
	// default to the latest commit of the `master` branch.
	Version *string `json:"version,omitempty" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AtomicRedTeamSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["guid"]; raw != nil && !ok {
		return fmt.Errorf("field guid in AtomicRedTeamSchemaJson: required")
	}
	if _, ok := raw["technique"]; raw != nil && !ok {
		return fmt.Errorf("field technique in AtomicRedTeamSchemaJson: required")
	}
	type Plain AtomicRedTeamSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AtomicRedTeamSchemaJson(plain)
	return nil
}

// Definition of an AWS CLI detonation
type AwsCliDetonatorSchemaJson struct {
	// Script corresponds to the JSON schema field "script".
	Script *string `json:"script,omitempty" yaml:"script,omitempty" mapstructure:"script,omitempty"`
}

// Matcher for a Datadog security signal
type DatadogSecuritySignalSchemaJson struct {
	// Name of the Datadog signal to match on (exact match)
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Severity of the Datadog signal to match on
	Severity *string `json:"severity,omitempty" yaml:"severity,omitempty" mapstructure:"severity,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DatadogSecuritySignalSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in DatadogSecuritySignalSchemaJson: required")
	}
	type Plain DatadogSecuritySignalSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DatadogSecuritySignalSchemaJson(plain)
	return nil
}

// Definition of a local command detonation
type LocalDetonatorSchemaJson struct {
	// AtomicRedTeam corresponds to the JSON schema field "atomicRedTeam".
	AtomicRedTeam *AtomicRedTeamSchemaJson `json:"atomicRedTeam,omitempty" yaml:"atomicRedTeam,omitempty" mapstructure:"atomicRedTeam,omitempty"`

	// Commands corresponds to the JSON schema field "commands".
	Commands []string `json:"commands,omitempty" yaml:"commands,omitempty" mapstructure:"commands,omitempty"`
}

// Definition of a remote command detonation
type RemoteDetonatorSchemaJson struct {
	// AtomicRedTeam corresponds to the JSON schema field "atomicRedTeam".
	AtomicRedTeam *AtomicRedTeamSchemaJson `json:"atomicRedTeam,omitempty" yaml:"atomicRedTeam,omitempty" mapstructure:"atomicRedTeam,omitempty"`

	// Commands corresponds to the JSON schema field "commands".
	Commands []string `json:"commands,omitempty" yaml:"commands,omitempty" mapstructure:"commands,omitempty"`
}

// Definition of a Stratus Red Team detonator
type StratusRedTeamDetonatorSchemaJson struct {
	// Attack technique ID of the Stratus Red Team technique to detonate (per
	// https://stratus-red-team.cloud/attack-techniques/list/)
	AttackTechnique *string `json:"attackTechnique,omitempty" yaml:"attackTechnique,omitempty" mapstructure:"attackTechnique,omitempty"`
}

// Schema for a Threatest test suite
type ThreatestSchemaJson struct {
	// The display name of the vulnerability
	Scenarios []ThreatestSchemaJsonScenariosElem `json:"scenarios" yaml:"scenarios" mapstructure:"scenarios"`
}

// The list of scenarios
type ThreatestSchemaJsonScenariosElem struct {
	// How to detonate the attack
	Detonate ThreatestSchemaJsonScenariosElemDetonate `json:"detonate" yaml:"detonate" mapstructure:"detonate"`

	// Expectations corresponds to the JSON schema field "expectations".
	Expectations []ThreatestSchemaJsonScenariosElemExpectationsElem `json:"expectations" yaml:"expectations" mapstructure:"expectations"`

	// Description of the scenario
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// How to detonate the attack
type ThreatestSchemaJsonScenariosElemDetonate struct {
	// AwsCliDetonator corresponds to the JSON schema field "awsCliDetonator".
	AwsCliDetonator *AwsCliDetonatorSchemaJson `json:"awsCliDetonator,omitempty" yaml:"awsCliDetonator,omitempty" mapstructure:"awsCliDetonator,omitempty"`

	// LocalDetonator corresponds to the JSON schema field "localDetonator".
	LocalDetonator *LocalDetonatorSchemaJson `json:"localDetonator,omitempty" yaml:"localDetonator,omitempty" mapstructure:"localDetonator,omitempty"`

	// RemoteDetonator corresponds to the JSON schema field "remoteDetonator".
	RemoteDetonator *RemoteDetonatorSchemaJson `json:"remoteDetonator,omitempty" yaml:"remoteDetonator,omitempty" mapstructure:"remoteDetonator,omitempty"`

	// StratusRedTeamDetonator corresponds to the JSON schema field
	// "stratusRedTeamDetonator".
	StratusRedTeamDetonator *StratusRedTeamDetonatorSchemaJson `json:"stratusRedTeamDetonator,omitempty" yaml:"stratusRedTeamDetonator,omitempty" mapstructure:"stratusRedTeamDetonator,omitempty"`
}

// Expectations
type ThreatestSchemaJsonScenariosElemExpectationsElem struct {
	// DatadogSecuritySignal corresponds to the JSON schema field
	// "datadogSecuritySignal".
	DatadogSecuritySignal *DatadogSecuritySignalSchemaJson `json:"datadogSecuritySignal,omitempty" yaml:"datadogSecuritySignal,omitempty" mapstructure:"datadogSecuritySignal,omitempty"`

	// The maximal time to wait for the assertion, written as a Go duration (e.g. 5m)
	Timeout string `json:"timeout,omitempty" yaml:"timeout,omitempty" mapstructure:"timeout,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreatestSchemaJsonScenariosElemExpectationsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ThreatestSchemaJsonScenariosElemExpectationsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["timeout"]; !ok || v == nil {
		plain.Timeout = "5m"
	}
	*j = ThreatestSchemaJsonScenariosElemExpectationsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreatestSchemaJsonScenariosElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["detonate"]; raw != nil && !ok {
		return fmt.Errorf("field detonate in ThreatestSchemaJsonScenariosElem: required")
	}
	if _, ok := raw["expectations"]; raw != nil && !ok {
		return fmt.Errorf("field expectations in ThreatestSchemaJsonScenariosElem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ThreatestSchemaJsonScenariosElem: required")
	}
	type Plain ThreatestSchemaJsonScenariosElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ThreatestSchemaJsonScenariosElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreatestSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["scenarios"]; raw != nil && !ok {
		return fmt.Errorf("field scenarios in ThreatestSchemaJson: required")
	}
	type Plain ThreatestSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ThreatestSchemaJson(plain)
	return nil
}
